name: Validate Production PR

on:
  pull_request:
    branches:
      - prod

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Check source branch
        run: |
          echo "Source branch: ${{ github.head_ref }}"

          if [ "${{ github.head_ref }}" != "main" ]; then
            echo "Only main can be merged into prod."
            exit 1
          fi
